### ISSUE TITLE
好赞！表达感谢！

### ISSUE THREAD

**Issue by Krue1** [xzxldl55/elementPlus-dynamic-theme#1]
为什么element-plus官方不直接内置这个设置主题色的方法。官方给出的只能一个个变量去改，怎么可能

**Comment by xzxldl55** [comment]
> 为什么element-plus官方不直接内置这个设置主题色的方法。官方给出的只能一个个变量去改，怎么可能

ElementPlus 给出了一套替换主题色的方法 https://element-plus.gitee.io/zh-CN/guide/theming.html，但是只能替换你预定好的主题色值，即我们只能使用我们自己预设好的几套主题色。

所以如果想要像这个项目里面这样我们通过后台配置动态传输来更换任意的主题色的话是没办法的，只能依靠 JS 替换变量。
by the way 这个变量替换的方法其实也就是 ElementPlus 官方给出的主题色设置的内部代码设置，我把他从 Scss 转成 JS过来用了😄
