### ISSUE TITLE
这个生成色序的算法和官方的颜色没有对应上？

### ISSUE THREAD

**Issue by chengkai2022** [xzxldl55/elementPlus-dynamic-theme#3]
![Snipaste_2024-07-18_15-33-10](https://github.com/user-attachments/assets/a7e07e9b-f2b8-44a1-9aec-2cb475376cc2)
同样的primary，生成的下面的几个颜色不一样？

**Comment by chengkai2022** [comment]
![Snipaste_2024-07-18_15-49-49](https://github.com/user-attachments/assets/cdcc5159-fe0b-447a-b683-dba58f8a4f38)
在暗色基调下这个white不能是白，要变成黑才行。

**Comment by xzxldl55** [comment]
> ![Snipaste_2024-07-18_15-33-10](https://private-user-images.githubusercontent.com/70818246/349859057-a7e07e9b-f2b8-44a1-9aec-2cb475376cc2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1ODQ1NzMsIm5iZiI6MTczMjU4NDI3MywicGF0aCI6Ii83MDgxODI0Ni8zNDk4NTkwNTctYTdlMDdlOWItZjJiOC00NGExLTlhZWMtMmNiNDc1Mzc2Y2MyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI2VDAxMjQzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ1MDdkYTA1ZmQ5ZWM1NmRjNGQ5ZjcwMmRiYTk1M2I4NDkzNGY2YTIzNTBkMTMzZDRmMjhjN2QyYjBjMGRkOTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.YBJ_xzOGetWZUD3B_wXRK8qYIHro8HDwr7BfYVOkV44) 同样的primary，生成的下面的几个颜色不一样？

确实，我这里没考虑到dark模式，light模式下是对的上的，dark模式要咋整的得研究看看👍

**Comment by xzxldl55** [comment]
![混合色](https://github.com/user-attachments/assets/28dae8b8-b1df-4a18-974d-2de7d335b830)

**Comment by xzxldl55** [comment]
仔细研究了下elementPlus的暗黑模式机制，可以看看这篇分享。
[elementPlus 自定义主题在暗黑模式下的问题探究
](https://juejin.cn/post/7442573821444390949)

**Comment by chengkai2022** [comment]
我自己解决的方案比较简单，就是根据color-scheme的值，去修改混合色的rgbWhite的值，生成的序列就是对的了，值为dark就把他改成黑.没去探究里面的原理。最近elementplus后面又加了一些颜色，感觉也可以探究学习下，不然还需要手动调整
